version: "3.8"

services:
  backend:
    container_name: backend-poizon
    build: .
    ports:
      - "8090:8081"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8081/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  grafana-storage: {}
  redis_data: {}
  prometheus_data: {}
