version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8081:8081"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8081/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 5s
